# Done to increase the memory available to gradle.
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=1.21.1
parchment_version=2024.11.17@zip
loader_version=0.17.2
fabric_version=0.116.6+1.21.1
fabric_kotlin_version=1.13.0+kotlin.2.1.0

# Mod Properties
mod_version=1.0.6
mod_group=com.pokeskies.skiescrates
mod_id=skiescrates
mod_name=SkiesCrates
